SWC-302: best guess is to pull offending call into server util (instead of client util).  Can't repro NoClassDefFoundError com/extjs/gxt/ui/client/widget/Layout in local environment